menu:
- {name: 'home', url: '/'}
- {name: 'research', url: '/research'} 
- {name: 'portfolio', url: '/portfolio'}
- {name: 'blog', url: '/blog'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

research:
- {name: 'Real-Time Imaging Using Deep Learning to Identify Rare Sperm Cells', url: 'real-time'}
- {name: 'Biophysical Profiling of Red Blood Cells Using Deep Learning', url: 'biophysical'}
- {name: 'Assessing Red Blood Cell Deformability Using Deep Learning', url: 'deformability'}
- {name: 'Self-Supervised Learning for Segmenting Cardiac Ultrasound Videos', url: 'self-supervised'}

courses:
- {name: 'MECH 423: Mechatronics Product Design', url: 'mecha-prod-design'}
- {name: 'MECH 421: Mechatronic System Instrumentation', url: 'mecha-system-instru'}
- {name: 'MECH 368: Electrical Instrumentation and Measurement', url: 'elec-instru'}

social:
- {icon: 'google_scholar', link: 'https://scholar.google.ca/citations?user=AF1z09QAAAAJ&hl=en&oi=ao'}
- {icon: 'github', link: 'https://github.com/lamoureuxe'}
#- {icon: 'twitter', link: 'https://twitter.com/elamox'}
#- {icon: 'instagram', link: 'https://instagram.com/erik_lamoureux'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/erik-lamoureux'}

contacts:
- {name: 'Erik Lamoureux', title: 'PhD Candidate', department: 'Mechanical Engineering', institution: 'University of British Columbia', institution_address: '2350 Health Sciences Mall, Vancouver, Canada', phone: '+1 (604) 341-4768', email: 'erik.s.lamoureux@gmail.com', office: 'Life Sciences Institute', social: 'Google Scholar, Github, and LinkedIn are linked below', image: 'assets/img/tractor.jpg'}
